### ISSUE TITLE
skill issue

### ISSUE THREAD

**Issue by ArtyomKor** [aquaismissing/INCS2bot#19]
надо сделать так, чтобы когда выпадал гав гав гав гав, то банило не сибиряка, а того, кто отправил мяу мяу мяу мяу

**Comment by ishakbas** [comment]
up

**Comment by SyberiaK** [comment]
Тогда уж мут на день.

**Comment by ArtyomKor** [comment]
> Тогда уж мут на день.

можно

**Comment by vladik4il** [comment]
помяукай
